### PR TITLE
upgrade proof -> 0.1.1

### PR DESCRIPTION
**Pull request by hainessss**
# What Changed

Upgraded proof to 0.1.1

# Why

Proof has changed quite a lot.

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
Could you give me access to push to your fork? @hainessss

**Comment by hainessss** [comment]
@hipstersmoothie sorry for the delay. Just gave you access

**Comment by hainessss** [comment]
Not sure where the syntax error that is failing the job is coming from.

**Comment by hainessss** [comment]
@hipstersmoothie Sorry to bother, but do you have any ideas on this error?

**Comment by hipstersmoothie** [comment]
So this upgrade isn't something we can do on the `master` branch right now. Since it is such a big change this will be a part of our 2.0 release https://github.com/intuit/design-systems-cli/pull/365#issuecomment-672394571

The only other breaking change that is going out is upgrading the storybook configuration to just be a `preset` + a function you call. Much better than the cli trying to mimic storybook.

If you need any help migrating to 2.0 I can help out.Before hitting merge I was gonna write a migration guide.

**Comment by hipstersmoothie** [comment]
Should be releasing 2.0 tomorrow

**Pull request closed without merging**
