### PR TITLE
Proof next

### PR DESCRIPTION
**Pull request by hipstersmoothie**
Update proof and pull in changes in master

# Release Notes

WDIO Breaking changes:

- host -> hostname in proof.config.js
- Change all tests to use wdio updated APIs
- Removal of assert from proof. Consumer provides their own assertion library now

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@hainessss I've made a PR to the `next` branch with your changes since this is a breaking change for users. @adierkens needs to test a few things out before we merge though.

**Comment by adierkens** [comment]
I'll test this out and make and fixes to proof tomorrow

**Comment by hipstersmoothie** [comment]
cc @hainessss

**Comment by adierkens** [comment]
Spent a good portion of today updating our internal builds to use this version. Made a few patches to proof, and updated the version here, but should otherwise be good to go. 

The only major changes I needed to make for our projects were mostly due to the wdio@6 upgrade: 

* `host` -> `hostname` in proof.config.js
* Change all tests to use wdio updated APIs

* Removal of `assert` from proof. I opted to use `expect` to match out jest tests.

**Comment by hipstersmoothie** [comment]
thanks for the proof stuff. i'll upgrade storybook to latest tomorrow and release 2.0

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in `v2.0.0-next.17` :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v2.0.0`](https://github.com/intuit/design-systems-cli/releases/tag/v2.0.0) :rocket:

**Pull request merged**
